// <auto-generated />
using MenuApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251011113111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuApi.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "View your dashboard",
                            Icon = "📊",
                            Name = "Dashboard",
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manage users",
                            Icon = "👥",
                            Name = "Users",
                            Url = "/users"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Application settings",
                            Icon = "⚙️",
                            Name = "Settings",
                            Url = "/settings"
                        },
                        new
                        {
                            Id = 4,
                            Description = "View and generate reports",
                            Icon = "📈",
                            Name = "Reports",
                            Url = "/reports"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
