name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # Vite build-time environment variables (VITE_ prefix required)
          # These get baked into the JavaScript bundle during build
          VITE_AZURE_CLIENT_ID: baa611a0-39d1-427b-89b5-d91658c6ce26
          VITE_AZURE_TENANT_ID: ae372c45-2e81-4d1c-9490-e9ac10250047
          VITE_AZURE_REDIRECT_URI: https://witty-flower-068de881e.2.azurestaticapps.net
          VITE_API_URL: https://func-menu-app-18436.azurewebsites.net/api
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_FLOWER_068DE881E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/frontend" # App source code path
          api_location: "" # Empty - using linked Azure Functions backend (configured in Azure Portal)
          output_location: "dist" # Vite builds to dist/ directory
          ###### End of Repository/Build Configurations ######

          # NOTE: After deployment, link the Azure Functions backend in Azure Portal:
          # 1. Go to Static Web App > APIs > Production
          # 2. Click "Link" and select your Azure Functions app (func-menu-app-18436)
          # 3. This will add "Azure Static Web Apps (Linked)" identity provider to Functions
          # 4. Functions will only be accessible through the Static Web App (not publicly)

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_FLOWER_068DE881E }}
          action: "close"
